# Generated by Django 2.1.5 on 2020-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AddField(
            model_name='register',
            name='_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
