# Generated by Django 2.1.5 on 2020-03-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptd', '0002_auto_20200307_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
