# Generated by Django 2.1.5 on 2020-03-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptd', '0003_auto_20200307_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='register1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(default='', max_length=20)),
                ('Upaswd', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
