# Generated by Django 2.1.5 on 2020-03-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptd', '0004_auto_20200307_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register1',
        ),
    ]
