# Generated by Django 2.1.5 on 2020-03-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apptd', '0005_delete_register1'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('Uname', models.CharField(default='', max_length=20)),
                ('Upaswd', models.IntegerField(default=0)),
            ],
        ),
    ]
