# Generated by Django 2.1.5 on 2020-03-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptd', '0006_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='_id',
            new_name='iid',
        ),
    ]
